FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY shared /app/shared
COPY /worker/requirements-cpu.txt .
RUN pip install --no-cache-dir -r requirements-cpu.txt
COPY /worker /app
CMD ["python", "worker.py"]